[package]
name = "adventofcode2019_12"
version = "0.1.0"
authors = ["Alex Dachin <alexdachin20@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
